spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cache-redis?useSSL=false
    username: root
    password: admin123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    password: yadech20
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 40000